<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="user">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data"    type="UserData"/>
                <xs:element name="support" type="Support"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="UserData">
        <xs:sequence>
            <xs:element name="id"         type="xs:positiveInteger"/>
            <xs:element name="email"      type="xs:string"/>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="last_name"  type="xs:string"/>
            <xs:element name="avatar"     type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Support">
        <xs:sequence>
            <xs:element name="url"  type="xs:anyURI"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
