<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="page"        type="xs:positiveInteger"/>
                <xs:element name="per_page"    type="xs:positiveInteger"/>
                <xs:element name="total"       type="xs:nonNegativeInteger"/>
                <xs:element name="total_pages" type="xs:positiveInteger"/>
                <xs:element name="data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" type="UserItem" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="support" type="Support"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="UserItem">
        <xs:sequence>
            <xs:element name="id"         type="xs:positiveInteger"/>
            <xs:element name="email"      type="xs:string"/>
            <xs:element name="first_name" type="xs:string"/>
            <xs:element name="last_name"  type="xs:string"/>
            <xs:element name="avatar"     type="xs:anyURI"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Support">
        <xs:sequence>
            <xs:element name="url"  type="xs:anyURI"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
